apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  default.server: |
    keycloak.z-box.local z-box.local {
        hosts {
              192.168.0.5 keycloak.z-box.local z-box.local
              fallthrough
        }
    }
